image: python:3.9

stages:
  - test
  - deploy

variables:
  POSTGRES_PASSWORD: password

test:
  services:
    - postgres:14.1
  cache:
    key:
      files:
        - poetry.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - venv
      - .cache/pip
  stage: test
  script:
    - python -m venv venv
    - . venv/bin/activate
    - make dev-deps
    - make lint
    - make migrate
    - alembic-autogen-check
    - make test

deploy:
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fastapi-boilerplate4.git || true
    - git push -f heroku HEAD:master
  stage: deploy
  only:
    - master

